Use real creadentials object at sahara tests
FakeDict doesn't have all attributes of Credentials object and produces
bad log message:

   AttributeError: 'FakeDict' object has no attribute 'insecure'

Let's use correct object and clean our logs.

Change-Id: Ic58e7482fcf65c8fa5ca1c359d19b7e5c55c42c3